[build-system]
requires = [
"setuptools>=60",
"setuptools-scm>=8.0",
"pandas >= 2.0.3",
"numpy >= 1.25.0",
"openpyxl >= 3.1.2",
"matplotlib >= 3.7.2",
"xlsxwriter >= 3.1.2"
]
build-backend = "setuptools.build_meta"

[project]
name = "vlinder_test"
dynamic = ["version"]
authors = [
  { name="Vlinder team" },
]
description = "Package for responsible business decision making"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
"pandas >= 2.0.3",
"numpy >= 1.25.0",
"openpyxl >= 3.1.2",
"matplotlib >= 3.7.2",
"xlsxwriter >= 3.1.2"
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
namespaces = true
where = ["src"]

[tool.setuptools.package-data]
"vlinder_test.data" = ["*.xlsx", ".md"]
"vlinder_test.data.beerwiser.xlsx" = ["*.xlsx"]
"vlinder_test.data.beerwiser.csv" = ["*.csv"]
"vlinder_test.data.beerwiser.json" = ["*.json"]
"vlinder_test.data.izz.xlsx" = ["*.xlsx"]
"vlinder_test.data.izz.csv" = ["*.csv"]
"vlinder_test.data.izz.json" = ["*.json"]
"vlinder_test.data.refugee.xlsx" = ["*.xlsx"]
"vlinder_test.data.refugee.csv" = ["*.csv"]
"vlinder_test.data.refugee.json" = ["*.json"]

[project.urls]
"Homepage" = "https://github.com/responsible-business-decision-making/trbs"
"Bug Tracker" = "https://github.com/responsible-business-decision-making/trbs/issues"