[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "vlinder_test"
version = "0.14"
authors = [
  {name="Vlinder team"},
]
description = "Package for responsible business decision making"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
"pandas >= 2.0.3",
"numpy >= 1.25.0",
"openpyxl >= 3.1.2",
"matplotlib >= 3.7.2",
"xlsxwriter >= 3.1.2",
]

[tool.hatch.build.targets.wheel]
only-include = ["src/vlinder_test", "docs"]

[tool.hatch.build.targets.wheel.sources]
"src" = ""
"docs" = "vlinder_test/docs"

[project.urls]
"Homepage" = "https://github.com/responsible-business-decision-making/trbs"
"Bug Tracker" = "https://github.com/responsible-business-decision-making/trbs/issues"